### ISSUE TITLE
Banner is pixelated in small device 

### ISSUE THREAD

**Issue by jkga** [gdgphilippines/ioextended2018#42]
**Browser**
Google Chrome | 66.0.3359.181 (Official Build) (64-bit)
OS | Linux
JavaScript | V8 6.6.346.32

**Screenshot**
![screenshot](https://lh3.googleusercontent.com/K7iJ_Ck9qkfaZNf19nrX4hhN0OvYxtq5NMIBJcWJF8G1xkz-R155CUL5jZDFKNRUPCXncTCqVzLxqHSeHKWR3pXANCiZSG-xYbo4VEkHmHnBjbzcb7cAA2O7Y4MqT1IxlCho3-4IKTKvSNAUbESFzBACDVplx-8KqqrFkJcr3LvBY_OPcuAstNvdYjRbPupeEtA_dmM1OzQvwfQ_nO_XY5fZKEa-lLt4NzBYq9ojRLWBmoaiZDSiB-NmN0C31dce_e8jQZhwKADJY2li7MuefPTY3E2LyOhBVhMPOaj-bD6WApvdWxHHSi2KdzQTzOqkNWN2aWjiXihYWcCHP-IrIOdYhEwXCon2pYP6hoaA0o0_RXU46BPSvMTRNLTSHc0an7EfVBOOp_bybRDRCHKhuCEvKkq1WpbEmZpsivgdv0ZWRHCsA3knGIwmkgl_crRbviu8zndlNFW5LKboqc_StW58HtovXbyM5Upq_zNLBcyjYwYukx3EzTZ0TqHIh50UxMvH1ob4go3vjFP1GVQh7NqPJWs5DvchZ0vROOJ6CGgbH5vxiccxCmFciMB523cM7-L0Cq-HTkECuChvI4vqhFpI9aQg9ZjLm9OPnGY=w428-h637-no)

**Comment by tjmonsi** [comment]
Image is not showing up. But yep, I'm editing them now
